- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "20230718200234049300000010.cbp29vmb0t7z.us-east-1.rds.amazonaws.com"
    login_user: "nenye"
    login_password: "nenyedevopproj"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:m
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "20230718200234049300000010.cbp29vmb0t7z.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "nenye" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "nenyedevopproj" }


