- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "20230718200234049300000010.cbp29vmb0t7z.us-east-1.rds.amazonaws.com" 
    login_user: "nenye"
    login_password: "nenyedevopproj"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "20230718200234049300000010.cbp29vmb0t7z.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "nenye" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "nenyedevopproj" }
